---
- name: Set the package state based on how Ansible is installed.
  set_fact:
    ansible_package_state: "{{ 'present' if ansible_install_method == 'package' else 'absent' }}"

# Setup/install tasks.
- name: Set up Ansible on RedHat.
  include_tasks: setup-RedHat.yml
  when:
    - ansible_facts.os_family == 'RedHat'
    - ansible_facts.distribution != 'Fedora'
    - ansible_install_method == 'package'

- name: Set up Ansible on Fedora.
  include_tasks: setup-Fedora.yml
  when:
    - ansible_facts.distribution == 'Fedora'
    - ansible_install_method == 'package'

- name: Set up Ansible on Ubuntu.
  include_tasks: setup-Ubuntu.yml
  when:
    - ansible_facts.distribution == 'Ubuntu'
    - ansible_install_method == 'package'

- name: Set up Ansible on Debian.
  include_tasks: setup-Debian.yml
  when:
    - ansible_facts.distribution == 'Debian'
    - ansible_install_method == 'package'

- name: Set up Ansible using Pip.
  include_tasks: setup-pip.yml
  when: ansible_install_method == 'pip'
